// Mock catalogue for the storefront home page. Emoji stand in for product
// photography until real assets are wired up.

export const categories = [
  { name: "Fruits &\nVegetables", art: "🍋", tint: "#fff3d6" },
  { name: "Breads &\nSweets", art: "🥖", tint: "#fbe7d2" },
  { name: "Frozen\nSeafoods", art: "🦀", tint: "#ffe0d9" },
  { name: "Raw\nMeats", art: "🥩", tint: "#ffdede" },
  { name: "Wines & Alcohol\nDrinks", art: "🍷", tint: "#f2e2ef" },
  { name: "Coffees and\nTeas", art: "☕", tint: "#eee3d6" },
  { name: "Milks and\nDairies", art: "🥛", tint: "#e4eefb" },
  { name: "Pet\nFoods", art: "🦴", tint: "#e6f1e2" },
];

export const brands = [
  {
    label: "Snack Brand",
    title: "New Snacks Release",
    art: "🍿",
    tint: "#efe6f7",
  },
  {
    label: "Happy Tea",
    title: "Happy Tea 100% Organic, From $29.0",
    art: "🍵",
    tint: "#e9efe1",
  },
  {
    label: "Sodic Drink",
    title: "Sodic Can Box 24 Pieces - 30% OFF",
    art: "🥤",
    tint: "#e2ecf6",
  },
  {
    label: "Meat Fresh",
    title: "Fresh Meat Sausage, BUY 2 GET 1",
    art: "🌭",
    tint: "#e4efe6",
  },
];

export const topSaverFeatured = {
  id: "ts-featured",
  category: "Drinks",
  brand: "Brand Name",
  title: "Est Bot's Water 300ml x 24 Pieces",
  art: "🧃",
  tint: "#eef3f7",
  price: 99.9,
  oldPrice: 105.5,
  rating: 4,
  reviews: 128,
  badge: "Sale Off",
  sold: 21,
  stock: 40,
};

export const topSaverProducts = [
  {
    id: "ts-1",
    category: "Raw Meats",
    brand: "Meat Brand",
    title: "British Beef Shank (10% Fat)",
    art: "🥩",
    tint: "#fde8e6",
    price: 12.99,
    oldPrice: 16.99,
    rating: 5,
    reviews: 64,
    badge: "Sale Off",
    sold: 20,
    stock: 40,
  },
  {
    id: "ts-2",
    category: "Breads & Sweets",
    brand: "Farmart",
    title: "Farmart Farmhouse Soft White Bread",
    art: "🍞",
    tint: "#fbf0dd",
    price: 14.7,
    rating: 4,
    reviews: 31,
    sold: 8,
    stock: 35,
  },
  {
    id: "ts-3",
    category: "Drinks",
    brand: "Brand Name",
    title: "Ice Band's Ester 350ml x 24 Pieces",
    art: "🍊",
    tint: "#fdecd9",
    price: 22.1,
    oldPrice: 27.0,
    rating: 4,
    reviews: 45,
    badge: "Sale Off",
    sold: 30,
    stock: 60,
  },
  {
    id: "ts-4",
    category: "Frozen Seafoods",
    brand: "Sea Fresh",
    title: "Atlantic Salmon Fillet Skin On 400g",
    art: "🐟",
    tint: "#e4eef7",
    price: 31.5,
    oldPrice: 38.0,
    rating: 5,
    reviews: 87,
    badge: "Hot",
    sold: 12,
    stock: 25,
  },
];

export const productTabs = [
  "All",
  "Fruits & Vegetables",
  "Frozen Seafoods",
  "Raw Meats",
  "Coffee & Teas",
  "Breads & Sweets",
  "Drinks",
  "Pet Foods",
  "Milks & Dairies",
];

export const bestSellerFeatured = {
  id: "bs-featured",
  stock: 48,
  brand: "Brand Name",
  title: "Tree Green Matcha Powder Can 250g",
  art: "🍵",
  tint: "#e9f1e4",
  price: 18.25,
  oldPrice: 24.0,
  rating: 4,
  reviews: 212,
  badge: "Sale Off",
  category: "Coffee & Teas",
};

export const bestSellers = [
  {
    id: "bs-1",
    stock: 26,
    brand: "Farmart",
    title: "Beef Bone Marrow Cut 500g",
    art: "🍖",
    tint: "#fbe3e1",
    price: 29.9,
    oldPrice: 34.5,
    rating: 4,
    reviews: 54,
    badge: "Sale Off",
    category: "Raw Meats",
  },
  {
    id: "bs-2",
    stock: 64,
    brand: "MarfFury",
    title: "US Yellow Melon Fresh Picked",
    art: "🍈",
    tint: "#fdf3d8",
    price: 10.9,
    oldPrice: 12.5,
    rating: 5,
    reviews: 96,
    category: "Fruits & Vegetables",
  },
  {
    id: "bs-3",
    stock: 18,
    brand: "Farmart",
    title: "Spiced Chorizo 6 Packs Grilled",
    art: "🌶️",
    tint: "#fbdedb",
    price: 8.6,
    rating: 4,
    reviews: 22,
    badge: "Hot",
    category: "Raw Meats",
  },
  {
    id: "bs-4",
    stock: 52,
    brand: "Farmart",
    title: "Oatmeal Creamy Drink 1L Carton",
    art: "🥛",
    tint: "#e6eefa",
    price: 9.2,
    oldPrice: 11.4,
    rating: 4,
    reviews: 40,
    badge: "Sale Off",
    category: "Milks & Dairies",
  },
  {
    id: "bs-5",
    stock: 31,
    brand: "Brand Name",
    title: "Coconut Bowl With Fresh Fruits",
    art: "🥥",
    tint: "#f1ece3",
    price: 22.14,
    oldPrice: 26.0,
    rating: 5,
    reviews: 73,
    category: "Fruits & Vegetables",
  },
  {
    id: "bs-6",
    stock: 0,
    brand: "Ocean Pick",
    title: "King Prawn Deveined Tail On 300g",
    art: "🦐",
    tint: "#fde7e3",
    price: 26.4,
    rating: 4,
    reviews: 38,
    category: "Frozen Seafoods",
  },
];

export const justLanding = [
  {
    id: "jl-1",
    stock: 44,
    brand: "Meat Brand",
    title: "Smoked Bacon Strips 250g Pack",
    art: "🥓",
    tint: "#fbe1de",
    price: 15.4,
    oldPrice: 18.9,
    rating: 4,
    reviews: 19,
    badge: "New",
    category: "Raw Meats",
  },
  {
    id: "jl-2",
    stock: 22,
    brand: "Farmart",
    title: "Roast Chicken Family Tray 1.2kg",
    art: "🍗",
    tint: "#fbeada",
    price: 24.9,
    rating: 5,
    reviews: 58,
    category: "Raw Meats",
  },
  {
    id: "jl-3",
    stock: 37,
    brand: "Olive Land",
    title: "Extra Virgin Olive Oil 750ml",
    art: "🫒",
    tint: "#eaf0dd",
    price: 19.75,
    oldPrice: 23.0,
    rating: 4,
    reviews: 27,
    badge: "New",
    category: "Fruits & Vegetables",
  },
  {
    id: "jl-4",
    stock: 58,
    brand: "Farmart",
    title: "Golden Honey Raw Jar 500g",
    art: "🍯",
    tint: "#fdf0d4",
    price: 13.3,
    rating: 5,
    reviews: 64,
    category: "Coffee & Teas",
  },
  {
    id: "jl-5",
    stock: 0,
    brand: "Brand Name",
    title: "Pet Dry Food Chicken Flavour 2kg",
    art: "🐾",
    tint: "#e3f0f4",
    price: 30.2,
    oldPrice: 36.0,
    rating: 4,
    reviews: 12,
    badge: "New",
    category: "Pet Foods",
  },
  {
    id: "jl-6",
    stock: 29,
    brand: "Dairy Day",
    title: "Greek Natural Yogurt 4 x 150g",
    art: "🍶",
    tint: "#e9eef7",
    price: 7.85,
    rating: 4,
    reviews: 33,
    category: "Milks & Dairies",
  },
];

// Extra stock that only appears on the listing route, so the catalogue is
// deeper than the handful of items the home page merchandises.
export const moreProducts = [
  {
    id: "mp-1",
    brand: "Farmart",
    title: "Baby Spinach Washed & Ready 200g",
    art: "🥬",
    tint: "#e6f1e2",
    price: 4.9,
    oldPrice: 6.5,
    rating: 4,
    reviews: 41,
    category: "Fruits & Vegetables",
    stock: 72,
  },
  {
    id: "mp-2",
    brand: "Dairy Day",
    title: "Farmhouse Salted Butter Block 250g",
    art: "🧈",
    tint: "#fdf3d8",
    price: 6.4,
    rating: 5,
    reviews: 88,
    category: "Milks & Dairies",
    stock: 35,
  },
  {
    id: "mp-3",
    brand: "Bean Road",
    title: "Single Origin Coffee Beans 500g",
    art: "☕",
    tint: "#eee3d6",
    price: 21.9,
    oldPrice: 28.5,
    rating: 5,
    reviews: 152,
    category: "Coffee & Teas",
    stock: 40,
  },
  {
    id: "mp-4",
    brand: "Ocean Pick",
    title: "Frozen Squid Rings 500g Pack",
    art: "🦑",
    tint: "#e4eef7",
    price: 17.25,
    oldPrice: 19.9,
    rating: 4,
    reviews: 26,
    category: "Frozen Seafoods",
    stock: 15,
  },
  {
    id: "mp-5",
    brand: "Farmart",
    title: "Sourdough Country Loaf 800g",
    art: "🥖",
    tint: "#fbe7d2",
    price: 8.75,
    rating: 5,
    reviews: 67,
    category: "Breads & Sweets",
    stock: 12,
  },
  {
    id: "mp-6",
    brand: "Pet Club",
    title: "Cat Treats Salmon Sticks 12 Pack",
    art: "🐟",
    tint: "#e3f0f4",
    price: 5.6,
    oldPrice: 7.2,
    rating: 4,
    reviews: 33,
    category: "Pet Foods",
    stock: 0,
  },
];

// Single source for any route that browses the whole shop.
export const catalogue = [
  topSaverFeatured,
  ...topSaverProducts,
  bestSellerFeatured,
  ...bestSellers,
  ...justLanding,
  ...moreProducts,
];
