import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`.
    "coverage/**",
    // Generated by `npm run test:e2e`.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
